Página da manutenção de departamentos
INF2-2019/aplicacao-web pull request #14
Opened 2019-11-05 02:01 UTC by PedroCesarMesquita

# [Grupo 6 | G] Página da manutenção de departamentos

Criada página web da manutenção de departamentos.

## Cartões

* [Cartão](https://trello.com/c/kejrzHBk/24-p%C3%A1gina-da-manuten%C3%A7%C3%A3o-de-departamentos)

## Observações

Não está completamente otimizada ainda.

2019-11-05 18:10 UTC, Jonatanc05 reviewed
Por questões de padronização, acho bom fazer um modal de confirmação para deletar departamento

2019-11-05 18:10 UTC, Jonatanc05 reviewed
Por questões de padronização, acho bom fazer um modal de confirmação para deletar departamento

2019-11-06 01:44 UTC, artguerra requested changes
Algumas coisas precisam mudar pra entrar no padrão:
- Toast estático
- Botão de editar deveria auto-preencher os inputs, já que não dá pra atualizar com 1 campo só (aparentemente)
- Estilização dos modais fora do padrão: botões deveriam ficar no footer, depois da primeira inserção o input continua verde
- Sem confimação de exclusão

2019-11-06 01:44 UTC, arthurcg2 commented on src/diario/departamentos/index.html
> +		<label id="toast" class="toast right" style="margin-right: 5px; background-color: #00E676">Bem-vindo</label>
?

2019-11-06 01:44 UTC, arthurcg2 commented on src/diario/departamentos/index.html
> +				<h2>Adicionar</h2>
Se eu não me engano, estamos usando h4 no título do modal

2019-11-06 01:44 UTC, arthurcg2 commented on src/diario/departamentos/index.html
> +		</div>
Não utilizado

2019-11-06 01:44 UTC, arthurcg2 commented on src/js/diario/departamentos/View.js
> +		toast.style.backgroundColor = "#D32F2F";
É melhor adicionar uma classe para adicionar essa cor pelo materialize

2019-11-06 01:44 UTC, arthurcg2 commented on src/js/diario/departamentos/View.js
> +		const toast = document.querySelector("#toast");
Toast deveria ser gerado dinamicamente e ter um tempo de vida (documentação do materialize tem muito disso)

2019-11-06 01:44 UTC, arthurcg2 commented on src/js/diario/departamentos/main.js
> +	var instances = M.Modal.init(elems);
Talvez dar um AutoInit geral possa ser melhor, se for usar toasts por exemplo

2019-11-06 02:15 UTC, WagnerACV commented
Transformar o botão "Bem-vindo" em um toast de erro. Desenvolver a responsividade.

2019-11-11 01:01 UTC, merged