Manutenção de etapas - Estilização e Organização
INF2-2019/aplicacao-web pull request #34
Opened 2019-11-11 14:10 UTC by chulesnt

# [Grupo 3] Manutenção de Etapas

- Separação das funções de manutenção em diferentes arquivos JS para melhor organização e visibilidade
- Colocando a estilização dentro dos padrões

## Cartões

## Observações

Nada a declarar.

2019-11-11 19:01 UTC, pedro-gandra requested changes

2019-11-11 19:01 UTC, pedro-gandra commented on src/js/diario/etapas/adiciona.js
> +			}
E se for diferente de 400 e 200? Ex: 403, 422, etc...
Tem que usa-los e colocar retorno para eles também

2019-11-11 19:01 UTC, pedro-gandra commented on src/js/diario/etapas/deleta.js
> +		}
Mesma coisa de antes

2019-11-11 19:01 UTC, pedro-gandra commented on src/js/diario/etapas/deleta.js
> +		}
Sugestão: criar uma função que manipula o toast ao invés de copiar e colar sempre

2019-11-11 19:01 UTC, pedro-gandra commented on src/js/diario/etapas/edita.js
> +		}
mesma coisa

2019-11-13 14:22 UTC, WagnerACV approved these changes

2019-11-13 14:22 UTC, merged